# Plugin information
plugin:
  name: Feedback Plugin
  description: Feedback plugin for OctoberCMS
  icon: icon-comment-o
  author: AvaloniumTeam
  homepage: https://github.com/avalonium/oc-feedback-plugin

# Plugin navigation
navigation:
  feedback:
    label: Feedback
    url: avalonium/feedback/requests
    icon: icon-comment-o
    sideMenu:
      requests:
        label: Requests
        url: avalonium/feedback/requests
        icon: icon-comment-o
        counter: \Avalonium\Feedback\Models\Request::countNewRequests
        counterLabel: New Requests